# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmKGLEo3iCp9Uda8pWIKUNpCvIghBjwa
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime, timedelta

# Función para generar datos dummy (Simulación)
# En el futuro, esto se reemplazará por una conexión a tu base de datos real
@st.cache_data
def get_data():
    history_start = datetime(2021, 1, 1)
    forecast_start = datetime(2024, 1, 1)
    dates = pd.date_range(start=history_start, end=forecast_start + timedelta(days=365), freq="MS")

    df = pd.DataFrame({'Fecha': dates})
    df['Tipo'] = np.where(df['Fecha'] < forecast_start, 'Histórico', 'Forecast')

    # Simulación de datos
    trend = np.linspace(100, 200, len(dates))
    seasonality = 20 * np.sin(2 * np.pi * np.arange(len(dates)) / 12)
    base = trend + seasonality + np.random.normal(0, 10, len(dates))

    df['Valor'] = base
    df['Forecast_AI'] = np.where(df['Tipo'] == 'Forecast', base * 1.05, np.nan)
    df['Limite_Sup'] = df['Forecast_AI'] * 1.15
    df['Limite_Inf'] = df['Forecast_AI'] * 0.85
    df.loc[df['Tipo'] == 'Forecast', 'Valor'] = np.nan

    return df

def show():
    st.title("Tablero de Control Principal")
    st.markdown("---")

    df = get_data()

    # KPIs
    k1, k2, k3, k4 = st.columns(4)
    next_val = df[df['Tipo']=='Forecast']['Forecast_AI'].iloc[0]

    k1.metric("Forecast Próximo Mes", f"{next_val:,.0f}", "5.2%")
    k2.metric("Ventas Mes Actual", f"{next_val*0.95:,.0f}", "-5.0%", delta_color="inverse")
    k3.metric("Precisión (MAPE)", "12.5%", "-1.5%", delta_color="inverse")
    k4.metric("Valor Inventario", "$5.4 M", "2.3%")

    # Gráfico
    st.subheader("Proyección de Demanda")
    fig = go.Figure()

    # Banda
    fig.add_trace(go.Scatter(
        x=df['Fecha'].tolist() + df['Fecha'].tolist()[::-1],
        y=df['Limite_Sup'].fillna(df['Valor']).tolist() + df['Limite_Inf'].fillna(df['Valor']).tolist()[::-1],
        fill='toself', fillcolor='rgba(0,123,255,0.2)', line=dict(color='rgba(255,255,255,0)'), name='Rango'
    ))
    # Líneas
    fig.add_trace(go.Scatter(x=df[df['Tipo']=='Histórico']['Fecha'], y=df[df['Tipo']=='Histórico']['Valor'], name='Real', line=dict(color='#343a40')))
    fig.add_trace(go.Scatter(x=df[df['Tipo']=='Forecast']['Fecha'], y=df[df['Tipo']=='Forecast']['Forecast_AI'], name='Forecast IA', line=dict(color='#007bff', dash='dash')))

    fig.update_layout(height=400, margin=dict(l=20, r=20, t=40, b=20), plot_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig, use_container_width=True)

    # Tabla Reciente
    st.subheader("Datos Recientes")
    recent = df.tail(12).copy()
    recent['Fecha'] = recent['Fecha'].dt.strftime('%Y-%m')
    st.dataframe(recent.set_index('Fecha'), use_container_width=True)