# -*- coding: utf-8 -*-
"""data_connection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmKGLEo3iCp9Uda8pWIKUNpCvIghBjwa
"""

import streamlit as st

def show():
    st.title("Conexión de Datos")
    st.markdown("---")

    tab1, tab2 = st.tabs(["📂 Carga Manual", "🔗 Conexión ERP"])

    with tab1:
        st.write("Sube tus archivos CSV históricos.")
        col1, col2 = st.columns(2)
        col1.file_uploader("Ventas Históricas", type="csv")
        col2.file_uploader("Inventario Actual", type="csv")
        st.button("Procesar Archivos", type="primary")

    with tab2:
        st.write("Configura la conexión a tu base de datos.")
        c1, c2 = st.columns(2)
        c1.selectbox("Tipo ERP", ["SAP", "Oracle", "Microsoft", "SQL"])
        c1.text_input("Host")
        c2.text_input("Usuario")
        c2.text_input("Contraseña", type="password")
        st.button("Test Conexión")