# -*- coding: utf-8 -*-
"""inventory.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmKGLEo3iCp9Uda8pWIKUNpCvIghBjwa
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

@st.cache_data
def get_inv_data():
    return pd.DataFrame({
        'Referencia': [f'SKU-{i:03d}' for i in range(1, 51)],
        'Bodega': np.random.choice(['Norte', 'Sur', 'Central'], 50),
        'Clasif_ABC': np.random.choice(['A', 'B', 'C'], 50, p=[0.2, 0.3, 0.5]),
        'Clasif_XYZ': np.random.choice(['X', 'Y', 'Z'], 50),
        'Stock_Actual': np.random.randint(0, 1000, 50),
        'Top_Green': np.random.randint(200, 600, 50)
    })

def show():
    st.title("Análisis de Inventario")

    df = get_inv_data()

    c1, c2 = st.columns([2,1])
    with c1:
        st.subheader("Matriz de Riesgo")
        fig = px.scatter(df, x="Top_Green", y="Stock_Actual", color="Clasif_ABC", size="Stock_Actual",
                         title="Stock Actual vs Meta (DDMRP)", color_discrete_sequence=px.colors.qualitative.Set1)
        # Línea de equilibrio
        fig.add_shape(type="line", x0=0, y0=0, x1=600, y1=600, line=dict(color="grey", dash="dash"))
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        st.subheader("Stock por Bodega")
        fig2 = px.pie(df, values='Stock_Actual', names='Bodega', hole=0.4)
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("Detalle SKU")
    st.dataframe(df, use_container_width=True)