# -*- coding: utf-8 -*-
"""planning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmKGLEo3iCp9Uda8pWIKUNpCvIghBjwa
"""

import streamlit as st
import pandas as pd
from datetime import datetime

def show():
    st.title("Planeación Colaborativa")
    st.info("Ajusta el pronóstico manualmente. Tus cambios se guardan automáticamente.")

    # Datos dummy
    data = {
        'Mes': pd.date_range(start="2024-01-01", periods=6, freq="MS"),
        'Forecast_AI': [1200, 1350, 1100, 1400, 1500, 1600]
    }
    df = pd.DataFrame(data)
    df['Ajuste_Usuario'] = df['Forecast_AI'] # Inicializar igual

    # Editor
    edited_df = st.data_editor(
        df,
        column_config={
            "Mes": st.column_config.DateColumn(format="YYYY-MM"),
            "Forecast_AI": st.column_config.NumberColumn("IA Sugerido", disabled=True),
            "Ajuste_Usuario": st.column_config.NumberColumn("Tu Pronóstico", required=True)
        },
        use_container_width=True,
        num_rows="fixed"
    )

    # KPI de Impacto
    diff = edited_df['Ajuste_Usuario'].sum() - edited_df['Forecast_AI'].sum()
    st.metric("Impacto de tus cambios (Unidades)", f"{diff:,.0f}", delta_color="off")

    if st.button("💾 Guardar Cambios", type="primary"):
        st.success("Cambios guardados en la base de datos.")